### ISSUE TITLE
FE: Password API implementation 08/13/16

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#46]
- [ ] Password reset button sends request to backend
- [ ] /password/reset endpoint send email with link to a frontend reset page
- [ ] Reset password page that takes in a reset token & username (thru URL) and requests a new password (w/ confirm), which all three are then submitted to /password/change endpoint
- [ ] /password/change endpoint should accept username, reset token, and new password; verify the reset token is valid, and update the password.
- [ ] /password/change should also support accepting a username/auth token + old password + new password to change the password
- [ ] Front end page, accessible from somewhere, that allows a logged in user to submit their old password and new password (w/ confirm)

**Comment by logicplace** [comment]
Requirements updated

**Comment by kbrimm** [comment]
Includes tasks #49 and #50.

**Comment by kbrimm** [comment]
Moving this back by a week to accommodate increased hardware effort.
